github_token: ENC[AES256_GCM,data:Dr1M1UkbUo6jDfpWA7oWTiOx137ZdYypa0fOjG9byvU58XNTgYy68MDkWLvXPHi3uCeu2l1kHbHvozZb5NqoLEtWwJbY67LELDUVFHsaDRLnJqBU1AwzmIVkgfKH,iv:pGgeS+4dJzalSl2WDUXcxisAfaCW+8ouT89bHy3ElsE=,tag:LV6XdmXaoUYoqsfVrjmagw==,type:str]
OVH_application_key: ENC[AES256_GCM,data:HDIBC4WZl1NdqUeK8mSl4w==,iv:+Zd6KpT/JQrTzZE8pfz1w1PmzBIdwtuNuO93qOg9RSw=,tag:m4d+e8NLe6qjO2Np46ep0g==,type:str]
OVH_application_secret: ENC[AES256_GCM,data:uImJlg5p/dLRAz4eZCgFCx1bapYcLDJXt22naBRvOyI=,iv:aygmFa0EXD78Puh/nMNdEd3FXCcxUyozGmjtiJyTUeE=,tag:I6KHLibm2iWK48AiFHzm4g==,type:str]
OVH_consumer_key: ENC[AES256_GCM,data:uYV/87aFrd2km6VWzynGkDQzraZZUHYLqfZzCkK/J3o=,iv:JuFuC+V2hsvuKSvdmn2ZrU+NDKzJ2me741fkUPS6qXM=,tag:h7QjeYQcALgtjtOhW6jXPg==,type:str]
ctfd_username: ENC[AES256_GCM,data:JWPnmTA=,iv:5YV98P21SO5xQDZH3mJDkDcU424fxP2wPjUxbtSVu3Q=,tag:7FRXwoYYvSdkabBm0sF7eQ==,type:str]
ctfd_password: ENC[AES256_GCM,data:8EkLl0RvFWJTy7Uan24qfOLxDVw=,iv:fBHiLni86CKQzXHUf4vRQWTWPBDPW/RVTtLXS+lCS5k=,tag:xQzv7/O25iGePjQP38FCPg==,type:str]
sops:
    age:
        - recipient: age1yn39pts4aj9mcs6mgncw3cy409kdatamqaez2mgnh73vrqg98udq0slsnc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ3doL0UzZTVvdnEwcTVa
            d3VtOTlGWHNkUkQ0dE9Jb1lnM0p4U1pVUUNBClZWb09MSGlWUVFHL2RJYlZ5Y0k5
            N2hrUEZoVmMvalhWOHFhTnNiSi9vam8KLS0tIG1LQmlJRjdSeHhqakNsdjI5Y1ZM
            cEk5aXJYSy9TWHBuRzNaZFdiSmxsWlEKAAoskANOYXFOCc8UNlvVmCEsnUsKbqMM
            g54X/BoxER7KHI57nIRxq+n5BxWv17BtisVz26lMUShgDx9yE0wGmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qv55na2rrfsj7cwkt30w08qr3ultpvewndrzj28f3pxym9hclqh8zafyqxq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHp5bUNIUSBBbE1hYjhy
            Vld5UzhEckhUR2JIcURuRVZGaUxhNkIyWS82aGtwY0tXSDllawpuTDdWUE5pRHVW
            QURHYllndEhPUWdWMUw1UVo1ZURlczlwL3N5WmJDT1VnCi0tLSA3ZC83RVgwa0JM
            VUtEN1l3QjFrLy8zZUo2WHpEY2lqY3BuUkNTUnQ1YTlVCngta+VQmTDaeFew630p
            30oLgQaabImXswZAFylRqV91VvgO6IFsifLrAVc7t3sDsE6O+ZfesLAuMoEQcuUH
            lcE=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T16:12:22Z"
    mac: ENC[AES256_GCM,data:QKczcsRTqLk2IIAmGR7X3N1fQYAMY8pRn99GLtfVXVyqOwVVJL5o6BpdVpnJmwFoo9eR7C7EMkjuh8ZX1vtUMkqXRHtTZd+5ffsPcCZQheZzuCM5y74uMSZ22SsJLlssykSRaU10fWp2L39RLHWinGKGfNGjis73vAAg9qsTwGg=,iv:Ic/0/X6iSBZWMXsChQ2kZx3/nJkST3/Fw2VlwzYw2Fk=,tag:gZmXFII9iqhuIbYZnQ/7CQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
